apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mini-project
spec:
  selector:
    matchLabels:
      app: k8s-mini-project
  template:
    metadata:
      labels:
        app: k8s-mini-project
    spec:
      containers:
      - name: k8s-mini-project
        image: k8s-mini-project:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000